# Generated by Django 5.2 on 2026-05-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
