# Generated by Django 5.2 on 2026-05-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspacemember_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
