# Generated by Django 5.2 on 2026-05-21 16:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_alter_workspacemember_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspacemember',
            old_name='members',
            new_name='member',
        ),
        migrations.AlterUniqueTogether(
            name='workspacemember',
            unique_together={('member', 'workspace')},
        ),
    ]
