# Generated by Django 5.2 on 2026-05-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descriptions',
            new_name='description',
        ),
    ]
