# Generated by Django 5.2 on 2026-05-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
